
<div dir=rtl >
<h1>قوانین انجمنی</h1>

قوانین انجمنی روابط و وابستگی‌های متقابل بین مجموعه بزرگی از اقلام داده‌ای را نشان می‌دهند.

مثال متداول در رابطه با کشف قوانین انجمنی "تحلیل سبد خرید" است.  در این فرایند با توجه به اقلام مختلفی که مشتریان در سبد خریدشان قرار می‌دهند، عادات و رفتار خرید مشتریان مورد تحلیل قرار می‌گیرد و می‌توان با شناسایی ارتباط بین محصولات، الگوهای تکرار شونده در حین خرید را بدست آورد.

سه پارامتر مهم:
- Support  میزان محبوبیت یک مجموعه آیتم را با توجه به دفعات حضور در تراکنش‌ها نشان می‌دهد.
- Confidence  احتمال خرید آیتم y در صورت خرید آیتم x را نشان می‌دهد. x -> y
- Lift   ترکیب دو پارامتر بالا می‌باشد.

برای پیاده سازی قوانین انجمنی در این تمرین، از الگوریتم Apriori که یکی از محبوب‌ترین و کارآمدترین الگوریتم‌های این حوزه است استفاده می‌کنیم.


<font color='Green'> پرسش:  تاثیر مقادیر مختلف پارامتر Lift را در احتمال وقوع نتیجه بررسی کنید.  </font>

<font color='blue'>پارامتر lift می‌تواند ۳ نوع مقدار بگیرد. یا برابر با ۱ است که یعنی بین اجزای قانون انجمنی هیچ ارتباطی وجود ندارد. یا مقدارش بیشتر از ۱ است که یعنی خرید y به شرط خرید x محتمل است. و یا مقدار کمتر از ۱ است که یعنی خرید y به شرط خرید x  محتمل نیست.</font>

</div>


<div dir=rtl >
<h1>الگوریتم Apriori</h1>

روش کار الگوریتم به این صورت است که یک  حداقل مقدار پشتیبانی در نظر گرفته    می‌شود و تکرارها با مجموعه آیتم‌های مکرر اتفاق می‌افتند. در صورتیکه  مجموعه‌ها و زیرمجموعه‌ها مقدار پشتیبانی کمتر از حد آستانه داشته باشند حذف می‌شوند. این روند تا زمانیکه امکان حذف وجود نداشته باشد ادامه می‌یابد.

در این بخش از تمرین می‌خواهیم الگوریتم apriori را بر روی مجموعه داده Hypermarket_dataset که شامل سفارشات خرید افراد از فروشگاه های مواد غذایی است اعمال کنیم.


</div>


<div dir=rtl >
<h1>آماده‌سازی داده</h1>

<font color='Green'>پرسش: برای شروع کار باید داده‌های دیتاست را در قالب ماتریس پراکنده که محصولات  خریداری شده در ستون‌ و شماره سفارشات خرید به عنوان شاخص (index) هستند آماده کنید.


برای راحتی کار محصولات خریداری شده در هر سفارش را با اعداد 0,1 کدگذاری کنید.

 نمونه ماتریس خروجی شما:

<img src="https://drive.google.com/uc?id=1eD0jan1ZbeYqSklgK--ks7oeY-MyTA3p"></img>

</div>

In [ ]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [ ]:
df = pd.read_csv ('Hypermarket_dataset.csv')
members = list(set(df['Member_number']))
items = list(set(df['itemDescription']))
transactions_dict = dict()
for m in members:
  transactions_dict[m] = [0 for _ in range(len(items))]
for ind in df.index:
  m = df['Member_number'][ind]
  i = df['itemDescription'][ind]
  transactions_dict[m][items.index(i)] = 1
df = pd.DataFrame.from_dict(transactions_dict).T
df.columns = items
df

,rice,canned beer,pastry,ham,curd,frozen potato products,candles,dish cleaner,tropical fruit,fruit/vegetable juice,...,beverages,flower soil/fertilizer,coffee,bathroom cleaner,cereals,citrus fruit,brown bread,potato products,pet care,waffles
1000,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1001,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1002,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1003,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1004,0,1,1,0,0,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4996,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4997,0,1,0,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4998,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4999,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
5000,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0


<div dir=rtl >
<h1>شناسایی الگوهای پر تکرار</h1>

<font color='Green'> پرسش:  با اعمال الگوریتم apriori و به ازای مقدار min_support = 0.07 تمامی الگوهای پر تکرار را تولید نمایید.

</div>

In [ ]:
frequent_items = apriori(df, min_support=0.07, use_colnames=True)
frequent_items

     support                                    itemsets
0   0.165213                               (canned beer)
1   0.177527                                    (pastry)
2   0.120831                                      (curd)
3   0.233710                            (tropical fruit)
4   0.124936                     (fruit/vegetable juice)
..       ...                                         ...
78  0.077476            (citrus fruit, other vegetables)
79  0.090816               (root vegetables, rolls/buns)
80  0.071832                  (citrus fruit, rolls/buns)
81  0.071832      (whole milk, yogurt, other vegetables)
82  0.082093  (whole milk, other vegetables, rolls/buns)

[83 rows x 2 columns]


<div dir=rtl >
<h1>استخراج قوانین انجمنی</h1>


<font color='Green'> پرسش: تابعی بنویسید که با گرفتن دو ورودی confidence و lift قوانین انجمنی حاصل را در خروجی نشان دهد. </br>
برای دو حالت خروجی خود را در گزارش ثبت کنید.


</div>

In [ ]:
r = association_rules(frequent_items, metric = "lift")
def rules(confidence, lift):
  filter = (r['confidence'] >= confidence) & (r['lift'] >= lift)
  filtered = r[filter]
  return filtered

In [ ]:
rules_final = rules(0.4, 1.2)
display(rules_final)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
86,"(whole milk, yogurt)",(other vegetables),0.150590,0.376603,0.071832,0.477002,1.266589,0.015119,1.191967
88,"(yogurt, other vegetables)",(whole milk),0.120318,0.458184,0.071832,0.597015,1.303003,0.016704,1.344507
92,"(whole milk, other vegetables)",(rolls/buns),0.191380,0.349666,0.082093,0.428954,1.226753,0.015174,1.138847
93,"(whole milk, rolls/buns)",(other vegetables),0.178553,0.376603,0.082093,0.459770,1.220834,0.014850,1.153947
94,"(other vegetables, rolls/buns)",(whole milk),0.146742,0.458184,0.082093,0.559441,1.220996,0.014859,1.229837

In [ ]:
rules_final = rules(0.5, 0.78)
display(rules_final)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(canned beer),(whole milk),0.165213,0.458184,0.087224,0.527950,1.152268,0.011526,1.147795
3,(pastry),(whole milk),0.177527,0.458184,0.091072,0.513006,1.119651,0.009732,1.112572
16,(bottled water),(whole milk),0.213699,0.458184,0.112365,0.525810,1.147597,0.014452,1.142615
24,(pip fruit),(whole milk),0.170600,0.458184,0.086968,0.509774,1.112598,0.008801,1.105239
29,(shopping bags),(whole milk),0.168291,0.458184,0.091329,0.542683,1.184422,0.014220,1.184772
30,(domestic eggs),(whole milk),0.133145,0.458184,0.070292,0.527938,1.152242,0.009287,1.147766
35,(yogurt),(whole milk),0.282966,0.458184,0.150590,0.532185,1.161510,0.020940,1.158185
36,(whipped/sour cream),(whole milk),0.154695,0.458184,0.079785,0.515755,1.125650,0.008906,1.118888
38,(sausage),(whole milk),0.206003,0.458184,0.106978,0.519303,1.133394,0.012591,1.127146
41,(other vegetables),(whole milk),0.376603,0.458184,0.191380,0.508174,1.109106,0.018827,1.101643
42,(newspapers),(whole milk),0.139815,0.458184,0.072345,0.517431,1.129310,0.008284,1.122775
45,(rolls/buns),(whole milk),0.349666,0.458184,0.178553,0.510638,1.114484,0.018342,1.107190
46,(bottled beer),(whole milk),0.158799,0.458184,0.085428,0.537964,1.174124,0.012669,1.172672
88,"(yogurt, other vegetables)",(whole milk),0.120318,0.458184,0.071832,0.597015,1.303003,0.016704,1.344507
94,"(other vegetables, rolls/buns)",(whole milk),0.146742,0.458184,0.082093,0.559441,1.220996,0.014859,1.229837